const baseProducts = [
  { id: 1, name: 'CodeStream Pro', desc: 'Enterprise IDE integration layer', price: 129.00, img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk9nYzTZeZX60F0-kDoekZiMIRWdfkWoW59Lhltk1MkvIUzQVpZD68A9ZGoPdPf3RR6zeDWPgTiUtThgQLq4MavMn9YLjUdAMfMdVNIB6NABvagYwhBRnGbF8LAPqg9VhPx-jhDeIGfju7aIDOVsMe3QiTWiR1FgVih7dAuNJlKShV1cnUEPkDelLzBu5tP6ks0woUwb4fHL69rGdF2xTFQO9PCp3iGDT_bPuF8VFzC0KUNsCv6QY7ivBuXDBvj-3QeJmD0_qKb7k', brand: 'Tech Core', sizes: ['S', 'M', 'L'], variants: { sizes: ['S', 'M', 'L'], colors: ['Space Gray', 'Silver'] } },
  { id: 2, name: 'InsightDash v2', desc: 'Real-time analytics powerhouse', price: 89.00, img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAKahR4_nlBEJW8ZvRHz_955h4FAcGLUjrA_XGWtKc5O7T04CYaIGR8cxIjwhZLniT7eDg52JtDlNVbC08FBPmRH6xl_uQ7R1mGr2R5oh47SAVkm7G2p7By_TTO0_yu-AjTjlt0xUP4XPPwPcbMw4Mv4LxUMwK5POPhMgTQb9WeDrq8-kLRbfawcEPWNput8_SBAtIhRbH1UqhI8f9r9sIaV6i3hN0FuMaX2Kar2RUgUeung4dL7bLcczg2berge1mEqZNRRLx_dE0', brand: 'Elite Series', sizes: ['M', 'L'], variants: { colors: ['Matte Black', 'Rose Gold'] } },
  { id: 3, name: 'Nexus Core', desc: 'Cloud infrastructure automation', price: 249.00, img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCaegf1Eqkc-1vnmH-4qAHVPN1Av9N8l94ljXICzec_zCeKVSG2oxCwtgzldWkVoQMfLumCZ0-CVwyo5f4bkemlmzOPr2O1PI6RNBK-1Fh480uMjE5Z6ILgSNOweppr3-TAslLtQqqE0qjIHkhMnobsKUN7vI7GJ0qdOVlUihus6QBpSbx5rI7_3V_nUnKyqFkq94o6eMJh5Z4ELsOxiUrYI_XvQaSA3c0v1-IIm1kCQcLNgMR-RQ2iC4B8FCCUJrjT_Xm-tMz0fis', brand: 'Tech Core', sizes: ['16GB', '32GB'] },
  { id: 4, name: 'UI Kit Ultra', desc: 'Complete Figma design ecosystem', price: 45.00, img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBN6DbTOmpJXq4NsFdyk3ASDWUvaVPSYZtaPSKQrOvquPtNPDz93N8_tz1W5YIUPFaBju4-9CKVCB3zY9bO3_Ls25iDsKqT2bkmZYfzoH7Nl79yGWyrfXSTMQb3pRXEbtqBAXq-QocsPwnjAvq2E1uzW2d2Ir0b8p00Zq4QPbnvlwruD0t5aX3GmzhG6RS-dw5LN721ejP4VtWvoQ3UA5QxAXMnufTyIWp-4n_hP12RNcTousRMaPFwFmNjR7FJnSP9iXfFHnp_k_8', brand: 'Studio Line', sizes: ['S'] },
  { id: 5, name: 'AdEngine X', desc: 'Marketing optimization algorithm', price: 199.00, img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDj4APuF-umgTS4Cp5tEzyrH_Oxk9qSZG5MXe3wxFhWMrNTqoHxxrkLi7-VKbDuCI8tYn5v9c7F_CMrx2n5zmWayoS2eEq9LIE_qHX5nSVglID2w7yiEB0_PodEz1PJK796O815jRZ4gL7JJQYbrgXeVX9T_U2fcow0B9VAvPPdDnPuWOrTIJh3Kb2l5SF881yns7zbp6NQMs2crcxHvPjWoVRZIpuv6I4bZ_HTOshsevHdkcQsiG_Yo7YrGJhQzdsGJ63TaK0IFfY', brand: 'Modern Essentials', sizes: ['8GB', '16GB'] },
  { id: 6, name: 'SecureVault', desc: 'Military-grade password manager', price: 12.00, img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5elrWoX0UOqEyUtRjZ5wBnhK83AgO4NNY3S33hmo6-jc9GgxzF4z6gTq11pEp5gsoblEuWdnKDuuFFvELkfaYGIn2WX-jpgoyJ1tylBwIkuMiK7oThVwQbXJnmLedl9G5QVzK8VtL7crmL1KHfoMc-rX8EC3_A5IQlP-vSZ-B2jxkfFHFl39p2iI3ffCG_jIISIY1NyLJ-Skw2FvOCwgb9vNGa5zHHuV8MSkVLfjSUf7wHkrJZCs09Moc2-DTLn6yFo1so-nWxKM', brand: 'Elite Series', sizes: ['S', 'M'] }
];

export const products = [
  ...baseProducts,
  ...baseProducts.map(p => ({ ...p, id: p.id + 6, name: p.name + ' Pro', price: p.price + 20, brand: p.id % 2 === 0 ? 'Studio Line' : 'Tech Core' })),
  ...baseProducts.map(p => ({ ...p, id: p.id + 12, name: p.name + ' Max', price: p.price + 50, brand: p.id % 3 === 0 ? 'Modern Essentials' : 'Elite Series' })),
  ...baseProducts.map(p => ({ ...p, id: p.id + 18, name: p.name + ' Lite', price: Math.max(10, p.price - 30), brand: p.id % 2 !== 0 ? 'Studio Line' : 'Tech Core' }))
];
