const baseProducts = [
  {
    id: 'prod-001',
    tenantId: 'tenant-demo',
    categoryId: 'cat-001',
    name: 'CodeStream Pro',
    description: 'Enterprise IDE integration layer',
    desc: 'Enterprise IDE integration layer',
    price: 129.00,
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBk9nYzTZeZX60F0-kDoekZiMIRWdfkWoW59Lhltk1MkvIUzQVpZD68A9ZGoPdPf3RR6zeDWPgTiUtThgQLq4MavMn9YLjUdAMfMdVNIB6NABvagYwhBRnGbF8LAPqg9VhPx-jhDeIGfju7aIDOVsMe3QiTWiR1FgVih7dAuNJlKShV1cnUEPkDelLzBu5tP6ks0woUwb4fHL69rGdF2xTFQO9PCp3iGDT_bPuF8VFzC0KUNsCv6QY7ivBuXDBvj-3QeJmD0_qKb7k',
    brand: 'Tech Core',
    attributes: { color: ['Space Gray', 'Silver'], size: ['S', 'M', 'L'] },
    skus: [
      { id: 'sku-001-1', productId: 'prod-001', price: 129.00, stock: 10, attributes: { color: 'Space Gray', size: 'M' } },
      { id: 'sku-001-2', productId: 'prod-001', price: 129.00, stock: 5, attributes: { color: 'Silver', size: 'L' } },
    ],
  },
  {
    id: 'prod-002',
    tenantId: 'tenant-demo',
    categoryId: 'cat-001',
    name: 'InsightDash v2',
    description: 'Real-time analytics powerhouse',
    desc: 'Real-time analytics powerhouse',
    price: 89.00,
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAKahR4_nlBEJW8ZvRHz_955h4FAcGLUjrA_XGWtKc5O7T04CYaIGR8cxIjwhZLniT7eDg52JtDlNVbC08FBPmRH6xl_uQ7R1mGr2R5oh47SAVkm7G2p7By_TTO0_yu-AjTjlt0xUP4XPPwPcbMw4Mv4LxUMwK5POPhMgTQb9WeDrq8-kLRbfawcEPWNput8_SBAtIhRbH1UqhI8f9r9sIaV6i3hN0FuMaX2Kar2RUgUeung4dL7bLcczg2berge1mEqZNRRLx_dE0',
    brand: 'Elite Series',
    attributes: { color: ['Matte Black', 'Rose Gold'], size: ['M', 'L'] },
    skus: [
      { id: 'sku-002-1', productId: 'prod-002', price: 89.00, stock: 8, attributes: { color: 'Matte Black', size: 'M' } },
      { id: 'sku-002-2', productId: 'prod-002', price: 89.00, stock: 3, attributes: { color: 'Rose Gold', size: 'L' } },
    ],
  },
  {
    id: 'prod-003',
    tenantId: 'tenant-demo',
    categoryId: 'cat-002',
    name: 'Nexus Core',
    description: 'Cloud infrastructure automation',
    desc: 'Cloud infrastructure automation',
    price: 249.00,
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCaegf1Eqkc-1vnmH-4qAHVPN1Av9N8l94ljXICzec_zCeKVSG2oxCwtgzldWkVoQMfLumCZ0-CVwyo5f4bkemlmzOPr2O1PI6RNBK-1Fh480uMjE5Z6ILgSNOweppr3-TAslLtQqqE0qjIHkhMnobsKUN7vI7GJ0qdOVlUihus6QBpSbx5rI7_3V_nUnKyqFkq94o6eMJh5Z4ELsOxiUrYI_XvQaSA3c0v1-IIm1kCQcLNgMR-RQ2iC4B8FCCUJrjT_Xm-tMz0fis',
    brand: 'Tech Core',
    attributes: { size: ['16GB', '32GB'] },
    skus: [
      { id: 'sku-003-1', productId: 'prod-003', price: 249.00, stock: 6, attributes: { size: '16GB' } },
      { id: 'sku-003-2', productId: 'prod-003', price: 279.00, stock: 4, attributes: { size: '32GB' } },
    ],
  },
  {
    id: 'prod-004',
    tenantId: 'tenant-demo',
    categoryId: 'cat-003',
    name: 'UI Kit Ultra',
    description: 'Complete Figma design ecosystem',
    desc: 'Complete Figma design ecosystem',
    price: 45.00,
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBN6DbTOmpJXq4NsFdyk3ASDWUvaVPSYZtaPSKQrOvquPtNPDz93N8_tz1W5YIUPFaBju4-9CKVCB3zY9bO3_Ls25iDsKqT2bkmZYfzoH7Nl79yGWyrfXSTMQb3pRXEbtqBAXq-QocsPwnjAvq2E1uzW2d2Ir0b8p00Zq4QPbnvlwruD0t5aX3GmzhG6RS-dw5LN721ejP4VtWvoQ3UA5QxAXMnufTyIWp-4n_hP12RNcTousRMaPFwFmNjR7FJnSP9iXfFHnp_k_8',
    brand: 'Studio Line',
    attributes: { size: ['S'] },
    skus: [
      { id: 'sku-004-1', productId: 'prod-004', price: 45.00, stock: 20, attributes: { size: 'S' } },
    ],
  },
  {
    id: 'prod-005',
    tenantId: 'tenant-demo',
    categoryId: 'cat-002',
    name: 'AdEngine X',
    description: 'Marketing optimization algorithm',
    desc: 'Marketing optimization algorithm',
    price: 199.00,
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDj4APuF-umgTS4Cp5tEzyrH_Oxk9qSZG5MXe3wxFhWMrNTqoHxxrkLi7-VKbDuCI8tYn5v9c7F_CMrx2n5zmWayoS2eEq9LIE_qHX5nSVglID2w7yiEB0_PodEz1PJK796O815jRZ4gL7JJQYbrgXeVX9T_U2fcow0B9VAvPPdDnPuWOrTIJh3Kb2l5SF881yns7zbp6NQMs2crcxHvPjWoVRZIpuv6I4bZ_HTOshsevHdkcQsiG_Yo7YrGJhQzdsGJ63TaK0IFfY',
    brand: 'Modern Essentials',
    attributes: { size: ['8GB', '16GB'] },
    skus: [
      { id: 'sku-005-1', productId: 'prod-005', price: 199.00, stock: 7, attributes: { size: '8GB' } },
      { id: 'sku-005-2', productId: 'prod-005', price: 229.00, stock: 3, attributes: { size: '16GB' } },
    ],
  },
  {
    id: 'prod-006',
    tenantId: 'tenant-demo',
    categoryId: 'cat-003',
    name: 'SecureVault',
    description: 'Military-grade password manager',
    desc: 'Military-grade password manager',
    price: 12.00,
    img: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB5elrWoX0UOqEyUtRjZ5wBnhK83AgO4NNY3S33hmo6-jc9GgxzF4z6gTq11pEp5gsoblEuWdnKDuuFFvELkfaYGIn2WX-jpgoyJ1tylBwIkuMiK7oThVwQbXJnmLedl9G5QVzK8VtL7crmL1KHfoMc-rX8EC3_A5IQlP-vSZ-B2jxkfFHFl39p2iI3ffCG_jIISIY1NyLJ-Skw2FvOCwgb9vNGa5zHHuV8MSkVLfjSUf7wHkrJZCs09Moc2-DTLn6yFo1so-nWxKM',
    brand: 'Elite Series',
    attributes: { size: ['S', 'M'] },
    skus: [
      { id: 'sku-006-1', productId: 'prod-006', price: 12.00, stock: 15, attributes: { size: 'S' } },
      { id: 'sku-006-2', productId: 'prod-006', price: 12.00, stock: 10, attributes: { size: 'M' } },
    ],
  },
];

export const products = [
  ...baseProducts,
  ...baseProducts.map(p => ({ ...p, id: `${p.id}-pro`, name: p.name + ' Pro', price: p.price + 20, brand: p.id.endsWith('2') || p.id.endsWith('4') ? 'Studio Line' : 'Tech Core', skus: p.skus.map(s => ({ ...s, id: `${s.id}-pro`, productId: `${p.id}-pro`, price: s.price + 20 })) })),
  ...baseProducts.map(p => ({ ...p, id: `${p.id}-max`, name: p.name + ' Max', price: p.price + 50, brand: p.id.endsWith('3') || p.id.endsWith('6') ? 'Modern Essentials' : 'Elite Series', skus: p.skus.map(s => ({ ...s, id: `${s.id}-max`, productId: `${p.id}-max`, price: s.price + 50 })) })),
  ...baseProducts.map(p => ({ ...p, id: `${p.id}-lite`, name: p.name + ' Lite', price: Math.max(10, p.price - 30), brand: p.id.endsWith('1') || p.id.endsWith('3') || p.id.endsWith('5') ? 'Studio Line' : 'Tech Core', skus: p.skus.map(s => ({ ...s, id: `${s.id}-lite`, productId: `${p.id}-lite`, price: Math.max(10, s.price - 30) })) })),
];
